POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im10b24iLCJpZCI6IjVkZWI3MjgyZTNhYmUwMzM3MGIxYjhmNiIsImlhdCI6MTU3NTcxOTgwMH0.tKqyWjMYiEAARGlBlxiITMzCajADE7ny-vOd-7YSVD4

{
    "title": "Execute Order 66",
    "author": "Emperor Palpatine",
    "url": "http://localhost:3003/testi66",
    "likes": 1000
}